### ISSUE TITLE
Remove Cruiser and Destroyer ships

### ISSUE THREAD

**Issue by struthj** [OSU-CS361-W17/group2_project3#5]
Players have requested to add and remove certain ships from the game to make game play more interesting and updated.

**Comment by zainkai** [comment]
Everything should be ready for you to strip Cruiser and Destroyer ships. Make sure to remove them from tests as well.

**Comment by olsenme** [comment]
This was completed. Sorry about the extra deletions. Not sure what happened. I did go and remove those ships  from the battleship model and made a pull request for that as well.
